rm_model: amp
obs_shape: ???
action_shape: ???
device: ${device}
batch_size: 32

pretrain_rm: false
disc_lr: 1e-4
hidden_dim: 256
input_dim: 64
expl_scale: 1
use_expl_reward: true
expl_update_interval: 10