_target_: diffusion_reward.rl.drqv2.agent.DrQV2Agent
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: ${lr}
critic_target_tau: 0.01
update_every_steps: 2
use_tb: ${use_tb}
num_expl_steps: 2000
hidden_dim: 1024
feature_dim: ${feature_dim}
stddev_schedule: ${stddev_schedule}
stddev_clip: 0.3